#define MICROPY_HW_BOARD_NAME "RC2 Dev Board"
#define MICROPY_HW_MCU_NAME "ESP32"
#define MICROPY_HW_BOARD_RC2



#define MODULE_CDISPLAY_ENABLED (1)
#define MODULE_BUZZER_ENABLED   (1)
#define MODULE_USB_ENABLED      (1)
#define MODULE_SENSOR_ENABLED   (1)
#define MODULE_SWITCH_ENABLED   (1)
